apiVersion: 1

datasources:
  - name: Fraud PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: fraud_db
    user: fraud_user
    secureJsonData:
      password: fraud_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true

